Test/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('webApp.urls', 'webapp'), namespace='webapp'))
]

webApp/urls.py
from django.conf.urls import url
from django.urls import path
from .views import categoryView, tagView, productView, signupView, loginView, logoutView

app_name = "webapp"


urlpatterns = [
    path(r'category/', categoryView.as_view(), name='category'),
    path(r'tag/', tagView.as_view(), name='tag'),
    path(r'product/', productView.as_view(), name='product'),
    path("", loginView, name="login"),
    url(r'signup/', signupView, name='signup'),
    path("logout", loginView, name="logout"),
]

webApp/models.py
from django.db import models
from django.core.validators import FileExtensionValidator


class category(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.name


class tag(models.Model):
    name = models.CharField(max_length=25, blank=False, null=False)

    def __str__(self):
        return self.name


class product(models.Model):
    category = models.ForeignKey(category, models.DO_NOTHING)
    tag = models.ForeignKey(tag, models.DO_NOTHING)
    name = models.CharField(max_length=25, blank=False, null=False)
    image = models.FileField(upload_to='static/image/', blank=False, null=False)
    description = models.TextField(max_length=100, blank=False, null=False)

webApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth import authenticate


class Frm_login(forms.Form):
    username = forms.CharField(required=True, widget=forms.EmailInput(
        attrs={'class': 'form-control', 'type': 'text', 'required': 'true'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control ', 'type': 'password', 'required': 'true', 'autocomplete': 'off'}))

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        kwargs = {'username': username}
        try:
            user = User.objects.get(**kwargs)
            if user.check_password(password):
                return user
        except User.DoesNotExist:
            return None
        user = authenticate(username=username, password=password)
        return user


class Frm_Category(forms.ModelForm):
    name = forms.CharField(required=True, max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control', 'required': 'true',}))

    class Meta:
        model = category
        fields = '__all__'


class Frm_Tag(forms.ModelForm):
    name = forms.CharField(required=True, max_length=25, widget=forms.TextInput(attrs={
        'class': 'form-control', 'required': 'true',}))

    class Meta:
        model = tag
        fields = '__all__'


class Frm_Product(forms.ModelForm):
    category = forms.ModelChoiceField(required=True, queryset=category.objects.all(), widget=forms.Select(
        attrs={'class':'form-control', 'required': 'true'}))
    tag = forms.ModelChoiceField(required=True, queryset=tag.objects.all(), widget=forms.Select(
        attrs={'class':'form-control', 'required': 'true'}))
    name = forms.CharField(required=True, max_length=100, widget=forms.TextInput(attrs={
        'class':'form-control', 'required': 'true'}))
    description = forms.CharField(required=True, max_length=100, widget=forms.Textarea(attrs={
        'class': 'form-control', 'required': 'true', 'rows':'3'}))
    image = forms.FileField(widget=forms.FileInput(attrs={'required': 'true', 'accept': 'image/*'}))

    class Meta:
        model = product
        fields = '__all__'

webApp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.views import View
from .models import product, tag, category
from django.http import HttpResponseRedirect
from .forms import *
from django.contrib.auth.models import User


def signupView(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def loginView(request):
    form_data = request.POST
    form = Frm_login(form_data)
    if form.is_valid():
        try:
            user_obj = User.objects.get(username=request.POST["username"])
        except User.DoesNotExist:
            user_obj = None
        if user_obj != None:
            user = form.login(request)
            if user:
                login(request, user)
                return redirect('webapp:product')
            else:
                messages.success(request, "Enter Valid User Name and Password.")
                return render(request, 'login.html', {'form': form})
        else:
            messages.success(request, "Enter Valid User Name.")
            return render(request, 'login.html', {'form': form})
    return render(request, 'login.html', {'form': form})


def logoutView(request):
    logout(request)
    return redirect("webapp:login")


class categoryView(View):
    form_class = Frm_Category
    initial = {'key': 'value'}
    template_name = 'category.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        objects = category.objects.all()
        return render(request, self.template_name, {'form': form, 'objects': objects})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/category/')
        return render(request, self.template_name, {'form': form})


class tagView(View):
    form_class = Frm_Tag
    initial = {'key': 'value'}
    template_name = 'tag.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        objects = tag.objects.all()
        return render(request, self.template_name, {'form': form, 'objects': objects})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/tag/')
        return render(request, self.template_name, {'form': form})


class productView(View):
    form_class = Frm_Product
    initial = {'key': 'value'}
    template_name = 'product.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        objects = product.objects.all()
        return render(request, self.template_name, {'form': form, 'objects': objects})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/product/')
        return render(request, self.template_name, {'form': form})

templates/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<div class="row">
    <div class="col-md-2">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'webapp:category' %}">Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:tag' %}">Tag</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:product' %}">Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:logout' %}">Logout</a>
          </li>
        </ul>
    </div>
    <div class="col-md-10 p-2">
        {% block content %}

        {% endblock %}
    </div>
</div>
</body>
</html>

templates/main.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class="col-md-6 align-items-center">
        {% block content %}

        {% endblock %}
    </div>
</div>
</body>
</html>

webApp/templates/category.html
{% extends 'index.html' %}

{% block content %}

<form action="{% url 'webapp:category' %}" method="post">
    {% csrf_token %}
    <div class="form-group row">
        <label for="id_name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-6">
            {{ form.name }}
        </div>
    </div>
    <button type="submit">Create</button>
</form>

{% for object in objects %}
{{object.name}} <br>
{% endfor %}

{% endblock %}

webApp/templates/login.html
{% extends 'main.html' %}

{% block content %}
{% for message in messages %}
<div class="alert text-danger" role="alert">
    <strong>Login failed!</strong> {{ message }}
</div>
{% endfor %}

<form class="p-2" action="{% url 'webapp:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group row">
        <label for="id_username" class="col-sm-2 col-form-label">UserName</label>
        <div class="col-sm-6">
            {{ form.username }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_password" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-6">
            {{ form.password }}
        </div>
    </div>
    <button type="submit">Login</button>
    <a href="{% url 'webapp:signup' %}"><button type="button">Sinup</button></a>cre
</form>

{% endblock %}

webApp/templates/product.html
{% extends 'index.html' %}

{% block content %}

<form action="{% url 'webapp:product' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
        <label for="id_category" class="col-sm-2 col-form-label">Category</label>
        <div class="col-sm-6">
            {{ form.category }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_tag" class="col-sm-2 col-form-label">Tag</label>
        <div class="col-sm-6">
            {{ form.tag }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-6">
            {{ form.name }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_description" class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-6">
            {{ form.description }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_image" class="col-sm-2 col-form-label">Image</label>
        <div class="col-sm-6">
            {{ form.image }}
        </div>
    </div>
    <button type="submit">Create</button>
</form>

{% for object in objects %}
{{object.name}} <br>
{% endfor %}

{% endblock %}

webApp/templates/signup.html
{% extends 'main.html' %}


{% block content %}

{% for message in messages %}
<div class="alert text-danger" role="alert">
    <strong>{{ message }}</strong>
</div>
{% endfor %}
<form class="p-2" action="{% url 'webapp:signup' %}" method="post">
    {% csrf_token %}
    <div class="form-group row">
        <label for="id_username" class="col-sm-2 col-form-label">UserName</label>
        <div class="col-sm-6">
            <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
        </div>
    </div>
    <div class="form-group row">
        <label for="id_password1" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-6">
            <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
        </div>
    </div>
    <div class="form-group row">
        <label for="id_password2" class="col-sm-2 col-form-label">Re-Enter Password</label>
        <div class="col-sm-6">
            <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
        </div>
    </div>
    <button type="submit">Create Account</button>
    <a href="{% url 'webapp:login' %}"><button type="button">Login</button></a>
</form>

{% endblock %}

webApp/templates/tag.html
{% extends 'index.html' %}

{% block content %}

<form action="{% url 'webapp:tag' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
        <label for="id_name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-6">
            {{ form.name }}
        </div>
    </div>
    <button type="submit">Create</button>
</form>

{% for object in objects %}
{{object.name}} <br>
{% endfor %}

{% endblock %}